export const products = [
  {
    id: "1",
    title: "proud",
    price: 15000,
    stock: 5,
    description: "algodon rustico",
    category: "remeras",
    imageUrl: "link",
  },
  {
    id: "2",
    title: "greg",
    price: 20000,
    stock: 2,
    description: "denim",
    category: "jeans",
    imageUrl: "link",
  },
  {
    id: "3",
    title: "living",
    price: 10000,
    stock: 2,
    description: "algodon rustico",
    category: "remeras",
    imageUrl: "link",
  },
  {
    id: "4",
    title: "race",
    price: 30000,
    stock: 2,
    description: "denim",
    category: "jeans",
    imageUrl: "link",
  },
];
